"use client";

import React from "react";
import Link from "next/link";
import { GlassCard } from "@/components/ui/GlassCard";
import { PrimaryButton } from "@/components/ui/PrimaryButton";
import { Badge } from "@/components/ui/Badge";
import { Award, CheckCircle2, ArrowRight, Bot, Sparkles, Download, Share2 } from "lucide-react";

export default function InterviewReportPage() {
  return (
    <div className="space-y-8 font-sans">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div className="space-y-1">
          <Badge variant="lime">INTERVIEW EVALUATION COMPLETE</Badge>
          <h1 className="font-display text-3xl font-bold text-brand-dark tracking-tight">
            AI Interview Feedback & Scorecard
          </h1>
          <p className="text-xs text-brand-muted">
            Evaluation generated by PrepWise AI Speech & Technical Assessment Engine.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <PrimaryButton variant="secondary" size="sm" icon={<Download className="w-3.5 h-3.5" />}>
            Download PDF
          </PrimaryButton>
          <Link href="/student/certificate">
            <PrimaryButton variant="primary" size="sm" icon={<ArrowRight className="w-3.5 h-3.5" />}>
              Unlock Certificate
            </PrimaryButton>
          </Link>
        </div>
      </div>

      {/* Main Score Overview */}
      <GlassCard variant="white" className="p-8 border-2 border-brand-blue/30 space-y-6">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6 items-center text-center md:text-left divide-y md:divide-y-0 md:divide-x divide-slate-100">
          <div className="space-y-1">
            <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">OVERALL SCORE</span>
            <p className="font-display font-extrabold text-4xl text-brand-blue">88 / 100</p>
            <Badge variant="lime">RECOMMENDED FOR HIRED</Badge>
          </div>

          <div className="space-y-1 md:pl-6">
            <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">TECHNICAL DEPTH</span>
            <p className="font-display font-extrabold text-2xl text-emerald-600">86%</p>
            <p className="text-[11px] text-slate-400">Data structures & logic</p>
          </div>

          <div className="space-y-1 md:pl-6">
            <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">VERBAL FLUENCY</span>
            <p className="font-display font-extrabold text-2xl text-brand-dark">90%</p>
            <p className="text-[11px] text-slate-400">142 words/min pace</p>
          </div>

          <div className="space-y-1 md:pl-6">
            <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">CONFIDENCE SCORE</span>
            <p className="font-display font-extrabold text-2xl text-purple-600">88%</p>
            <p className="text-[11px] text-slate-400">Eye contact & posture</p>
          </div>
        </div>
      </GlassCard>

      {/* Breakdown Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        <div className="lg:col-span-8 space-y-6">
          <GlassCard variant="white" className="p-6 space-y-4">
            <h3 className="font-display font-bold text-base text-brand-dark">Question Responses & AI Feedback</h3>

            <div className="space-y-4 text-xs">
              <div className="p-4 bg-slate-50 rounded-2xl space-y-2 border border-slate-200">
                <div className="flex justify-between items-center font-bold">
                  <span>Q1: Stack vs Queue Difference</span>
                  <Badge variant="success">92 / 100</Badge>
                </div>
                <p className="text-slate-600 italic">
                  "Explained LIFO and FIFO correctly with plate stack and ticket counter examples."
                </p>
                <div className="text-brand-blue font-semibold">
                  AI Feedback: Perfect clarity! Consider mentioning space complexity (O(1) auxiliary space) for bonus points.
                </div>
              </div>

              <div className="p-4 bg-slate-50 rounded-2xl space-y-2 border border-slate-200">
                <div className="flex justify-between items-center font-bold">
                  <span>Q2: SQL vs NoSQL Concurrency</span>
                  <Badge variant="blue">84 / 100</Badge>
                </div>
                <p className="text-slate-600 italic">
                  "Mentioned ACID compliance vs eventual consistency."
                </p>
                <div className="text-brand-blue font-semibold">
                  AI Feedback: Solid explanation of transactions. Elaborate further on Sharding and CAP theorem.
                </div>
              </div>
            </div>
          </GlassCard>
        </div>

        <div className="lg:col-span-4 space-y-6">
          <GlassCard variant="dark" className="p-6 space-y-4">
            <h4 className="font-display font-bold text-base">Key Strengths</h4>
            <ul className="space-y-2 text-xs text-slate-300">
              <li className="flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-brand-lime" /> Clear articulation and structured responses
              </li>
              <li className="flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-brand-lime" /> Strong understanding of Data Structures
              </li>
            </ul>

            <Link href="/student/certificate">
              <PrimaryButton variant="lime" fullWidth size="md" icon={<ArrowRight className="w-4 h-4" />}>
                View Placement Certificate
              </PrimaryButton>
            </Link>
          </GlassCard>
        </div>
      </div>
    </div>
  );
}
